language: node_js
node_js:
  - '14'
  - '12'
  - '10'
os:
  - linux
  - osx
osx_image: xcode11
dist: focal
addons:
  apt:
    packages:
    - nasm
  snaps:
    - name: rustup
      confinement: classic
  homebrew:
    packages:
    - rustup
    - nasm
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then rustup install stable && rustup default stable; else rustup-init -y; fi
